// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: EnergyMonitor_2

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 0 );
lv_obj_set_y( ui_Label1, -25 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_Label1,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_Label1,"SOLAR INVERTER");
lv_obj_add_state( ui_Label1, LV_STATE_DISABLED );     /// States
lv_obj_clear_flag( ui_Label1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_Label1, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_letter_space(ui_Label1, -1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Label1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 0 );
lv_obj_set_y( ui_Label2, -3 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_Label2,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_Label2,"load, %");
lv_obj_add_state( ui_Label2, LV_STATE_DISABLED );     /// States
lv_obj_clear_flag( ui_Label2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_Label2, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Label2, -1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Label2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelValue = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_LabelValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelValue, 0 );
lv_obj_set_y( ui_LabelValue, 33 );
lv_obj_set_align( ui_LabelValue, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_LabelValue,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_LabelValue,"XXX%");
lv_obj_add_state( ui_LabelValue, LV_STATE_DISABLED );     /// States
lv_obj_add_flag( ui_LabelValue, LV_OBJ_FLAG_OVERFLOW_VISIBLE );   /// Flags
lv_obj_clear_flag( ui_LabelValue, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_LabelValue, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_letter_space(ui_LabelValue, -1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_LabelValue, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelValue, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_EnergyLoadArc = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_EnergyLoadArc, 274);
lv_obj_set_height( ui_EnergyLoadArc, 242);
lv_obj_set_x( ui_EnergyLoadArc, 16 );
lv_obj_set_y( ui_EnergyLoadArc, 12 );
lv_obj_set_align( ui_EnergyLoadArc, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_EnergyLoadArc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_arc_set_value(ui_EnergyLoadArc, 90);
lv_obj_set_style_arc_width(ui_EnergyLoadArc, 25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_EnergyLoadArc, false, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_EnergyLoadArc, lv_color_hex(0x46B508), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_EnergyLoadArc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_EnergyLoadArc, 25, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_EnergyLoadArc, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_opa(ui_EnergyLoadArc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_ImageLineArcIndicator = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_ImageLineArcIndicator, 44);
lv_obj_set_height( ui_ImageLineArcIndicator, 44);
lv_obj_set_x( ui_ImageLineArcIndicator, 127 );
lv_obj_set_y( ui_ImageLineArcIndicator, -88 );
lv_obj_set_align( ui_ImageLineArcIndicator, LV_ALIGN_CENTER );
lv_obj_add_state( ui_ImageLineArcIndicator, LV_STATE_USER_1 | LV_STATE_USER_2 );     /// States
lv_obj_clear_flag( ui_ImageLineArcIndicator, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_arc_set_value(ui_ImageLineArcIndicator, 100);
lv_arc_set_bg_angles(ui_ImageLineArcIndicator,0,360);
lv_obj_set_style_arc_color(ui_ImageLineArcIndicator, lv_color_hex(0x3E3E3E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_ImageLineArcIndicator, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_ImageLineArcIndicator, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_ImageLineArcIndicator, lv_color_hex(0x358A06), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_arc_opa(ui_ImageLineArcIndicator, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_arc_color(ui_ImageLineArcIndicator, lv_color_hex(0x3E3E3E), LV_PART_MAIN | LV_STATE_USER_2 );
lv_obj_set_style_arc_opa(ui_ImageLineArcIndicator, 255, LV_PART_MAIN| LV_STATE_USER_2);

lv_obj_set_style_pad_left(ui_ImageLineArcIndicator, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_ImageLineArcIndicator, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_ImageLineArcIndicator, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_ImageLineArcIndicator, 10, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_ImageLineArcIndicator, lv_color_hex(0x3E3E3E), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_ImageLineArcIndicator, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_ImageLineArcIndicator, 3, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_ImageLineArcIndicator, lv_color_hex(0x46B508), LV_PART_INDICATOR | LV_STATE_USER_1 );
lv_obj_set_style_arc_opa(ui_ImageLineArcIndicator, 255, LV_PART_INDICATOR| LV_STATE_USER_1);
lv_obj_set_style_arc_width(ui_ImageLineArcIndicator, 12, LV_PART_INDICATOR| LV_STATE_USER_1);
lv_obj_set_style_arc_color(ui_ImageLineArcIndicator, lv_color_hex(0x3E3E3E), LV_PART_INDICATOR | LV_STATE_USER_2 );
lv_obj_set_style_arc_opa(ui_ImageLineArcIndicator, 255, LV_PART_INDICATOR| LV_STATE_USER_2);
lv_obj_set_style_arc_width(ui_ImageLineArcIndicator, 3, LV_PART_INDICATOR| LV_STATE_USER_2);

lv_obj_set_style_opa(ui_ImageLineArcIndicator, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_ImageLine = lv_img_create(ui_Screen1);
lv_img_set_src(ui_ImageLine, &ui_img_bolt_fill_white_png);
lv_obj_set_width( ui_ImageLine, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageLine, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImageLine, 126 );
lv_obj_set_y( ui_ImageLine, -89 );
lv_obj_set_align( ui_ImageLine, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ImageLine, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_ImageLine, LV_SCROLLBAR_MODE_OFF);

ui_ImageBoilerArcIndicator = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_ImageBoilerArcIndicator, 44);
lv_obj_set_height( ui_ImageBoilerArcIndicator, 44);
lv_obj_set_x( ui_ImageBoilerArcIndicator, -127 );
lv_obj_set_y( ui_ImageBoilerArcIndicator, -88 );
lv_obj_set_align( ui_ImageBoilerArcIndicator, LV_ALIGN_CENTER );
lv_obj_add_state( ui_ImageBoilerArcIndicator, LV_STATE_USER_1 | LV_STATE_USER_2 );     /// States
lv_obj_clear_flag( ui_ImageBoilerArcIndicator, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_arc_set_value(ui_ImageBoilerArcIndicator, 100);
lv_arc_set_bg_angles(ui_ImageBoilerArcIndicator,0,360);
lv_obj_set_style_arc_color(ui_ImageBoilerArcIndicator, lv_color_hex(0x3E3E3E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_ImageBoilerArcIndicator, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_ImageBoilerArcIndicator, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_ImageBoilerArcIndicator, lv_color_hex(0xEEA600), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_arc_opa(ui_ImageBoilerArcIndicator, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_arc_color(ui_ImageBoilerArcIndicator, lv_color_hex(0x3E3E3E), LV_PART_MAIN | LV_STATE_USER_2 );
lv_obj_set_style_arc_opa(ui_ImageBoilerArcIndicator, 255, LV_PART_MAIN| LV_STATE_USER_2);

lv_obj_set_style_pad_left(ui_ImageBoilerArcIndicator, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_ImageBoilerArcIndicator, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_ImageBoilerArcIndicator, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_ImageBoilerArcIndicator, 10, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_ImageBoilerArcIndicator, lv_color_hex(0x3E3E3E), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_ImageBoilerArcIndicator, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_ImageBoilerArcIndicator, 3, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_ImageBoilerArcIndicator, lv_color_hex(0xE1A418), LV_PART_INDICATOR | LV_STATE_USER_1 );
lv_obj_set_style_arc_opa(ui_ImageBoilerArcIndicator, 255, LV_PART_INDICATOR| LV_STATE_USER_1);
lv_obj_set_style_arc_width(ui_ImageBoilerArcIndicator, 12, LV_PART_INDICATOR| LV_STATE_USER_1);
lv_obj_set_style_arc_color(ui_ImageBoilerArcIndicator, lv_color_hex(0x3E3E3E), LV_PART_INDICATOR | LV_STATE_USER_2 );
lv_obj_set_style_arc_opa(ui_ImageBoilerArcIndicator, 255, LV_PART_INDICATOR| LV_STATE_USER_2);
lv_obj_set_style_arc_width(ui_ImageBoilerArcIndicator, 3, LV_PART_INDICATOR| LV_STATE_USER_2);

lv_obj_set_style_opa(ui_ImageBoilerArcIndicator, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_ImageBoiler = lv_img_create(ui_Screen1);
lv_img_set_src(ui_ImageBoiler, &ui_img_water_waves_orange_png);
lv_obj_set_width( ui_ImageBoiler, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageBoiler, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImageBoiler, -128 );
lv_obj_set_y( ui_ImageBoiler, -89 );
lv_obj_set_align( ui_ImageBoiler, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageBoiler, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageBoiler, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageBoiler,78);
lv_obj_set_style_img_recolor(ui_ImageBoiler, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_ImageBoiler, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

}
